### ISSUE TITLE
Should deprecated types be analyzed?

### ISSUE THREAD

**Issue by keith-turner** [revelc/apilyzer-maven-plugin#16]
I think deprecated members are not analyzed, howerver I saw a deprecated type in the list of Types i the report.  So I am not sure if deprecated classes members are analyzed.

**Comment by ctubbsii** [comment]
By default, they aren't analyzed, but they'll still show up in the list to analyze, because no reflection has been done yet to see the deprecated annotation when that list is generated.

**Comment by busbey** [comment]
configurable option?

**Comment by ctubbsii** [comment]
This was available in 1.0.0 release.
