### ISSUE TITLE
NPE when there is no excludes section

### ISSUE THREAD

**Issue by keith-turner** [revelc/apilyzer-maven-plugin#23]
I tried running Apilyzer 1.0.1 with only an allows section in the config.  When I did this it failed with NPE trying to process the excludes.

**Comment by ctubbsii** [comment]
@keith-turner Is this still an issue in version 1.1.0?

**Comment by keith-turner** [comment]
I think I fixed this

**Comment by ctubbsii** [comment]
Okay, I'll change the milestone back to 1.1.0 for now. We can revisit if there's more to address.
